apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerDenyWithoutResourceConstraints
metadata:
  name: containerdenywithoutresourceconstraints
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - DaemonSet
      - Deployment
      - StatefulSet
