version: "2"
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
  settings:
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -SA1019 # Do not block the build if deprecated functions or packages are used.
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
