apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PspDenyPrivileged
metadata:
  name: pspdenyprivileged
spec:
  match:
    kinds:
    - apiGroups:
      - policy
      kinds:
      - PodSecurityPolicy
