name: Update CLI Docs
on:
  push:
    branches-ignore:
      - main
    paths:
    - '.github/gendocs/**'
    - 'internal/commands/*.go'
    - '!internal/commands/*_test.go'

jobs:
  update-docs:
    name: Update CLI Docs
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: checkout source
        uses: actions/checkout@v3

      - name: generate docs
        run: |
          go mod download
          go run .github/gendocs/konstraint.go

      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: konstraint-bot
          author_email: konstraint-bot@dev.null
          message: 'generate updated cli docs'
          add: 'docs/cli'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
